### PR TITLE
Update dev dependencies, Nodejs 20 (lts) support

### PR DESCRIPTION
**Pull request by aindlq**
# Why

Because currently recommended node 12 is not supported anymore.

# What

We need to enable node js legacy mode because our dependencies are quite old. So this can be considered a quickfix. Proper fix would involve updating some dependencies, like React etc.

This PR depends on https://github.com/researchspace/YASGUI.YASR/pull/1 . So you merge that one I would update package.json to point to the updated version. Right now it points to my fork.

Also this PR uses `sass` package instead of `node-sass`. Which is also deprecated, requires python2 and for me it was not working reliably with the latest node. 

# How To Test

Try to run the build with the latest node js LTS release.

### CODE REVIEW

**Comment by aindlq** [comment]
@dianat
I've updated all major dev dependencies like webpack, typescript and sass to the latest versions so now the whole thing can be used with the latest node without "hacks". 

Potentially there can be some subtle issues because new node resolves dependencies slightly differently.

**Comment by dianat** [comment]
> @dianat I've updated all major dev dependencies like webpack, typescript and sass to the latest versions so now the whole thing can be used with the latest node without "hacks".
> 
> Potentially there can be some subtle issues because new node resolves dependencies slightly differently.

Hi Artem,
I've just tried it and the big issues are see are when creating entities of any type and the Resource configuration section in the admin page. Maybe I missed something in what you wrote in terms of testing (I will checked out the PR):

Please see attached. Thank you!

Screenshot 2024-04-22 at 16 16 31

Screenshot 2024-04-22 at 16 15 47

**Comment by aindlq** [comment]
Hi @dianat. Thank you for looking into the PR. I fixed the issue with styles. But I can't reproduce the issue with forms, I tried with clean checkout and everything seems to be working.

**Comment by aindlq** [comment]
@dianat try to remove node_modules folder before starting the system, latest node is using slightly different dependencies resolution

**Comment by dianat** [comment]
I've just tried it with the changes and it's looking fine now. I had some test custom-app in my runtime-data. We will do a bit more testing, but this is great!

**Comment by aindlq** [comment]
@dianat thanks for merging! :tada:

**Comment by giancrys84** [comment]
@aindlq There's a problem in the css used in the header and I think it's related to this PR. 
Screenshot 2024-05-08 at 19 30 18
In the example you can see the .form-control class has style from _table.scss and _forms.scss (from bootstrap-sass) but it's not using at all the style from the component in form.scss (image below)
Screenshot 2024-05-08 at 19 33 54

**Pull request merged**
