### PR TITLE
SSO with SAML2 and OIDC (Keycloak).

### PR DESCRIPTION
**Pull request by aindlq**
This is is major refactoring of the SSO feature to make sure that it works with as little config as possible.

* Adds support for SAML2, OpenID Connect (OIDC) and more specifically Keycloak OIDC flavor.
* Enable SecretResolver functionality, can be used to resolve application secrets from outside storage, currently only simple environment variable storage is implemented.

# Keycloak OIDC
<b>environment.prop</b>
```
platformBaseIri=http://localhost:10214
sso=keycloak
```
or with JAVA system properties:
```
-Dconfig.environment.platformBaseIri=http://localhost:10214
-Dconfig.environment.sso=keycloak
```

<b>shiro-sso-params.ini</b>
```
[main]
keycloakBaseUri.value = http://local-keycloak:8090/auth
realm.value = my_realm
clientId.value = my_client
clientSecret.value = 1731e501-5800-4075-af7e-eccf8319a4fd
```
or with environment variables:
```
RS_SSO_KEYCLOAK_BASE_URI: "http://local-keycloak:8090/auth"
RS_SSO_KEYCLOAK_REALM: "my_realm"
RS_SSO_CLIENT_ID: "my_client"
RS_SSO_CLIENT_SECRET: "1731e501-5800-4075-af7e-eccf8319a4fd"
```

# Generic OIDC
<b>environment.prop</b>
```
platformBaseIri=http://localhost:10214
sso=oidc
```
or with JAVA system properties:
```
-Dconfig.environment.platformBaseIri=http://localhost:10214
-Dconfig.environment.sso=oidc
```

<b>shiro-sso-params.ini</b>
```
[main]
oidcDiscoveryUri.value = http://local-keycloak:8090/auth/realms/my_realm/.well-known/openid-configuration
roleJsonPaths.value = \$.realm_access.roles, \$.resource_access.my_client.role
clientId.value = my_client
clientSecret.value = 1731e501-5800-4075-af7e-eccf8319a4fd
```
or with environment variables:
```
RS_SSO_OIDC_DISCOVERY_URI: "http://local-keycloak:8090/auth/realms/my_realm/.well-known/openid-configuration"
RS_SSO_OIDC_ROLE_JSON_PATHS: "$.realm_access.roles, $.resource_access.my_client.role"
RS_SSO_CLIENT_ID: "my_client"
RS_SSO_CLIENT_SECRET: "1731e501-5800-4075-af7e-eccf8319a4fd"
```

# SAML2
<b>environment.prop</b>
```
platformBaseIri=http://localhost:10214
sso=saml2
```
or with JAVA system properties:
```
-Dconfig.environment.platformBaseIri=http://localhost:10214
-Dconfig.environment.sso=saml2
```

<b>shiro-sso-params.ini</b>
```
[main]
serviceProviderEntityId.value = my_client_saml
identityProviderMetadataResourceUrl = http://local-keycloak:8090/auth/realms/my_realm/protocol/saml/descriptor
```

or with environment variables:
```
RS_SSO_SAML2_SERVICE_PROVIDER_ENITYT_ID: "my_client_saml"
RS_SSO_SAML2_IDENTITY_PROVIDER_METADATA_RESOURCE_URL: "http://local-keycloak:8090/auth/realms/my_realm/protocol/saml/descriptor"
```

When ResearchSpace is started one can download Sp Metadata XML file from `localhost:10214/rest/security/getSaml2SpMetadata`. This metadata file can be used to create SAML2 client in your IdP (e.g in Keycloak when creating new client for realm).

### CODE REVIEW

**Comment by lklic** [comment]
Hi @aindlq 

I got this up and running with an external instance of Keycloak relatively quickly (using a docker setup for both)

I added the details to the environment variables first (in the RS docker .env file), and got the following error at boot:

`researchspace_1      | 2021-02-16 16:57:43 ERROR [main] (GuiceServletConfig.java:66) - Error notifying InjectionListener org.apache.shiro.guice.InitializableInjectionListener@234c5e41 of org.researchspace.security.sso.SSOEnvironment.
researchspace_1      |  Reason: org.apache.shiro.config.UnresolveableReferenceException: The object with id [{RS_SSO_KEYCLOAK_BASE_URI}] has not yet been defined and therefore cannot be referenced.  Please ensure objects are defined in the order in which they should be created and made available for future reference.`

I then moved the config to **shiro-sso-params.ini** and it worked fine. I found that I just needed to add the roles in keycloak and assign them to each user to be able to log into RS.

The Logout link also takes me to the keycloak instance where I get an error "invalid redirect url". Not sure if there is something i need to configure there in keycloak? It does not clear the session, as I can go back into RS after clicking logout.

That's all the testing I have done for now, I will do some more tomorrow and document my steps for integrating into docs.

**Comment by lklic** [comment]
I also stumbled upon the user "profile" at resource/User:admin

This "profile" data could also be stored in Keycloak, since it allows for custom fields. One could then use the REST API of keyclaok to pull in these data. Since Keycloak allows for user registration, they could fill in all of this info at the time of registration or later. That could be one easy way to solve the permissions issue of users being able to modify their profile information.

**Comment by aindlq** [comment]
@lklic thanks for testing, how exactly did you add env variables. I believe `.env` file just sets variable for `docker-compose.yml` one, it doesn't automatically propagate these variables to containers. 

So you need to modify `environment` in the docker-compose and propagate variables like:
```
environment:
  RS_SSO_CLIENT_SECRET: ${RS_SSO_CLIENT_SECRET}
```

or use something like [env-file](https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file), which is a better idea I believe, so one can create `.security-env` file, put all variables there and then refer to it from the platform compose.

**Comment by aindlq** [comment]
btw, I've just quickly tried [identity brokering](https://www.keycloak.org/docs/latest/server_admin/#_identity_broker) with keycloak and it works pretty well. I connected keycloak to github and was able to login with my github credentials:

image

so this can be a good alternative for user registration on public instances, one can use github, twitter, google, etc. - see [social idp](https://www.keycloak.org/docs/latest/server_admin/#social-identity-providers)

**Comment by lklic** [comment]
@aindlq thanks for the tip!

that was a silly mistake on the docker-compose file.

Any hint on how to make the logout work properly?

also, on your .env config above you have commas after each entry, I don't think this is correct, can you confirm?

**Comment by aindlq** [comment]
@lklic no need for commas, edited.

**Comment by aindlq** [comment]
@lklic hm, logout is working for me without any additional configuration, are you using custom app with modified `header.hbs`?
In the `header.hbs` logout link should point to `/logout`, previously I think it was pointing to `/login`:
```
            <bs-menu-item href="/logout" title='logout'>
              <div class="user-dropdown_item">
                <i class="rs-icon rs-icon-logout rs-xs-none"></i>
                <span>Logout</span>
              </div>
            </bs-menu-item>
```

What happens if you go directly to logout url [localhost:10214/logout](localhost:10214/logout) ?

**Comment by lklic** [comment]
Hi @aindlq,

A few questions/suggestions:

- For troubleshooting, it would be helpful for a user to be able to see the roles that they have assigned to them. 
- It would also be helpful for admins to be able to manage roles in the UI, so that they can modify the permissions there. Would this be possible to implement?
- When a new role is assigned to a user, they need to log out and then log back in to have that role apply. Would it be possible to make the role apply instantly?
- If user registration is enabled, we have the option to use their email as the login. It would be helpful to have another field during the registration (like "display name") that would allow them to control the way that their name is shown on annotations/assertions, etc. That field would have to be mapped to RS as well, would this be possible?
- If we have other fields (like affiliation) that the user can fill out during the registration process, it would be nice to have these mapped to RS. I am not sure if it is better to do this mapping through the SSO component or through federation using the Keycloak REST api. If you think it's better to do through the REST API we can write the connector for that and create a PR. Let me know what you prefer.


Thanks!

**Comment by aindlq** [comment]
Hi @lklic,

> For troubleshooting, it would be helpful for a user to be able to see the roles that they have assigned to them.

yep, I'll add helper to expose it in the UI.


> When a new role is assigned to a user, they need to log out and then log back in to have that role apply. Would it be possible to make the role apply instantly?

hm, I don't see how one can notify the system that something changed on the keycloack side. 
But it should be possible to logout user from keycloack admin console. So when you change the role, you can logout the user, so next time when it access ResearchSpace instance, user would need to re-login and as side-effect get new roles.
Keycloack 12 supports backchannel logout - https://github.com/keycloak/keycloak/pull/7272,  but I can't find the way to trigger it from keycloack admin console. 


> It would also be helpful for admins to be able to manage roles in the UI, so that they can modify the permissions there. Would this be possible to implement?

Why do you need that? My assumption is that the list of roles is not going to change too often, so UI for it is a bit too much and my personal opinion is that doesn't worth the effort. But we can show list of roles with corresponding permissions in the admin area.

> If user registration is enabled, we have the option to use their email as the login. It would be helpful to have another field during the registration (like "display name") that would allow them to control the way that their name is shown on annotations/assertions, etc. That field would have to be mapped to RS as well, would this be possible?
> If we have other fields (like affiliation) that the user can fill out during the registration process, it would be nice to have these mapped to RS. I am not sure if it is better to do this mapping through the SSO component or through federation using the Keycloak REST api. If you think it's better to do through the REST API we can write the connector for that and create a PR. Let me know what you prefer.

I think it can be a pain to manage and it sounds to complex and error prone. Most likely you want to have `Affiliation` field value as URI, right? I bet that keycloak form config is not too sophisticated. So I think it is best to keep user info in the system as RDF. We can use `semantic-form`, connect fields to authorities and expand it as needed.

**Comment by lklic** [comment]
As far as the roles, it's fine not to have a UI for that, it's more for troubleshooting permissions issues. Sometimes it's hard to figure out what the implications are for some components.

For keeping user data as RDF, we have some privacy issues that are a bit more difficult to deal with, since all of our RS instances are fully open with SPARQL access. By keeping user data in there, including affiliations and emails, these data could then be harvested by third parties. The other reason is that we have one central keycloak instance for multiple RS instances, so users only need to create one login and enter their data once.

User data in Keycloak is easy to manage and is stored as a key:value pair, that you can define when creating your user registration forms. I am not that up to speed on OIDC so I don't know if there is a way to make a simple mapping to this data other than through the API.

Thanks,
L

**Comment by lklic** [comment]
Hi @aindlq 

I have just tested remote SPARQL authentication with this docker image and it is not working.

I am not getting anything in the log, only `Unsuccessful HTTP response` when I run a query against the repository.

Steps to reproduce:

- add a repository using sparql basic authentication on a separate RS instance
- tested with both default admin/admin login as well as a user that is in Keycloak with admin permissions
- tested remote sparql query on an instance with a shiro.ini file and verified that it works fine

Thanks,
Lukas

**Comment by aindlq** [comment]
Hi @lklic, 

basic auth is going to work only with locally defined users, by default they are disabled when sso is enabled, to enable local users add `enableLocalUsers=true` to the `environment.prop` file. You then should be able to login with users defined in the `shiro.ini` file by directly going to http://localhost:10214/login, or by using local users credentials in the basic auth.

**Comment by lklic** [comment]
thanks @aindlq!

Tested and I can confirm this is working!

**Review by lklic — APPROVED** [review]
LGTM!!

**Pull request merged**
