### PR TITLE
Added anonymous users for the keycloak sso

### PR DESCRIPTION
**Pull request by DawsonMacPhee**
@aindlq These are the changes we discussed. We decided to fully disable the default login page and replace it with keycloak (for our use case this is best, we don't want users finding the default login page at all). Let me know if there's anything that is going to be changed!

### CODE REVIEW

**Comment by lklic** [comment]
I haven’t looked at the code yet, but will this disable to local login page when local auth is enabled together with keycloak? If so this may create some problems for us and make it impossible to have auth enabled sparql repositories together with keycloak login. 

Thanks

**Comment by DawsonMacPhee** [comment]
Yes, currently this is disabling the local login page. The local user login system is being used to process anonymous users and keycloak is being used for everything else. As I said, for our use case in lincs, we elected to completely get rid of the local login page as we don't have a use for it and don't want our users finding it. 

This is something that could be fixed via another config parameter. Something like "disableLocalLoginPage={true/false}" in platform opts that could allow you to toggle between the complete removal of the local login page and another state that allows for a separate sso login endpoint.

**Comment by lklic** [comment]
Thanks! I think it would be much better to add this option as a config parameter, could you update the PR?

**Comment by DawsonMacPhee** [comment]
Requested changes are made:

Config Parameter
disableLocalLogin=true/false (false by default)

When true: SSO login page can be found at /login. Local login page cannot be accessed
When false: SSO login page can be found at /sso-login. Local login page can be found at /login (Note: authc.loginUrl is set to the local login page NOT the sso login page)

**Comment by aindlq** [comment]
@DawsonMacPhee thank you for the contribution!

just few comments so it is clear to everyone what is going on:

so currently anonymous user works with SSO only if `-Dconfig.environment.enableLocalUsers=true`, because anonymous user permission are taken from local `shiro.ini` file.  Which has somehow undesirable side effect that all users from `shiro.ini` file become available by default. Also prior to this PR it was not possible to initiate SSO workflow when anonymous user was enabled.

@DawsonMacPhee @lklic  I would say it should be other way around, by default local login page should be disabled when SSO is enabled, because there is much less room to make a configuration mistake that makes system more open than desirable. 

@DawsonMacPhee :
- Could you please rename `disableLocalLogin` to `enableLocalLogin` and make it false by default for SSO and true for all other strategies like local shiro file and ldap. Just add one more argument to `addSSOLogin` function and set default value depending on login strategy where it is invoked.
- When it is SSO and `enableLocalLogin` is true then bind `/local-login` path to it, to make sure that `/login` always pointing to default login strategy.

**Comment by DawsonMacPhee** [comment]
You want me to move local login to `/local-login` ? Right now the local login page is served at `login`, it would have to get moved too?

**Comment by aindlq** [comment]
> You want me to move local login to /local-login

only when SSO is enabled together with local login.

**Comment by DawsonMacPhee** [comment]
> only when SSO is enabled together with local login.

So, the login page template should also be found at `/local-login` then? Changing the filter without changing the login page breaks the login. Pressing the login button just refreshes the login page without logging in the user.

**Comment by aindlq** [comment]
You are right, `login` is hard-coded in the org.researchspace.rest.LoginApplication :(. OK, then keep it as is.

**Comment by aindlq** [comment]
@DawsonMacPhee thanks!

**Pull request merged**
